<?php 
$host='127.0.0.1:3306';
$usr=$pw='root';
$dbname='sb233';$rpath='..';
$texttable=$uptext='text';$fmraw='raw';$fmode='mode';
$filepath=$rpath.'/files/';
$textpath=$rpath.'/texts/';
$uppage='page';
$uppp='pp';
$joentry='entries';
$buffer=4096*8;
$upfile='file';$upzip='zip';$uphasfile='hasfile';$updel='del';
$jofn='name';$getfile='get';
$josize='size';$joresentry="responses";
$joresponse='status';
$jook='ok';$jofail='fail';$jotime='time';
$jomessage='msg';
$txsvfile='saveasfile';
$upcond='cond';
$nonexist=0;$failure=-1;$success=1;
$updiv=',';$peek=24;$upid='id';
?>